name: Cypress Test on Push
run-name: ${{ github.actor }} is running e2e 🚀
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-varsion: [17.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }} 🖥️
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules 🛠️
              run: npm install
            - name: start project 🏗️
              run: npm start &
            - name: Start Local Server
            - name: Run Cypress tests
              run: npx cypress run --config baseUrl=http://localhost:3000

            - name: Upload Cypress artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: cypress-results
                  path: cypress/videos cypress/screenshots
            - name: Upload test results
              uses: actions/upload-artifact@v1
              with:
                  name: test-results
                  path: cypress/reports
