name: GitHub Actions Main
run-name: ${{ github.actor }} is running out GitHub Actions 🚀
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-varsion: [17.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }} 🖥️
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules 🛠️
              run: npm install
            - name: build project 🏗️
              run: npm run build
            - name: linter ❕
              run: npm run lint
            - name: run tests 🔬
              run: npm run test
            - name: run e2e 🤖
              run: npm run cypress
            - name: Upload Cypress artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: cypress-results
                  path: cypress/videos cypress/screenshots
